import type {
  AspectRatio,
  CategoryId,
  DeviceType,
  Insert,
  InsertStatus,
  PlaybackMode,
} from "./types"

export const PROJECT_VERSION = "v0.9-gs-screenkit"
export const PROJECT_NAME = "screen inserts"
export const PROJECT_SUBTITLE = "гремучая смесь / prop playback system"

export type CategoryMeta = {
  id: CategoryId
  label: string
  accent: string
  tint: string
}

export const CATEGORIES: CategoryMeta[] = [
  { id: "phones", label: "phones", accent: "var(--accent-orange)", tint: "rgba(255,159,28,0.14)" },
  { id: "cctv", label: "cctv", accent: "var(--accent-red)", tint: "rgba(239,71,111,0.14)" },
  { id: "trackers", label: "trackers", accent: "var(--accent-purple)", tint: "rgba(108,99,255,0.16)" },
  { id: "tv-news", label: "tv news", accent: "var(--accent-blue)", tint: "rgba(47,128,237,0.14)" },
  { id: "bank", label: "bank", accent: "var(--accent-green)", tint: "rgba(34,197,94,0.14)" },
  { id: "hq-monitors", label: "hq monitors", accent: "var(--accent-cyan)", tint: "rgba(76,201,240,0.14)" },
]

export const categoryMeta = (id: CategoryId): CategoryMeta =>
  CATEGORIES.find((c) => c.id === id) ?? CATEGORIES[0]

export const DEVICES: { id: DeviceType; label: string; aspect: AspectRatio }[] = [
  { id: "phone", label: "phone", aspect: "9:16" },
  { id: "monitor", label: "monitor", aspect: "16:9" },
  { id: "tv", label: "tv", aspect: "16:9" },
  { id: "tablet", label: "tablet", aspect: "16:10" },
  { id: "projector", label: "projector", aspect: "16:9" },
  { id: "cctv", label: "cctv", aspect: "4:3" },
]

export const PLAYBACK_MODES: { id: PlaybackMode; label: string; note: string }[] = [
  { id: "clean", label: "clean", note: "crisp generated source frame" },
  { id: "filmed", label: "filmed", note: "filmed from screen: moiré, bloom, reflections" },
  { id: "dirty", label: "dirty", note: "dirty playback: compression, cctv artifacts, dropped frames" },
]

export const STATUSES: { id: InsertStatus; accent: string }[] = [
  { id: "draft", accent: "var(--text-muted)" },
  { id: "ready", accent: "var(--accent-green)" },
  { id: "needs review", accent: "var(--accent-orange)" },
  { id: "shooting", accent: "var(--accent-red)" },
]

export const statusAccent = (s: InsertStatus): string =>
  STATUSES.find((x) => x.id === s)?.accent ?? "var(--text-muted)"

export const INSERTS: Insert[] = [
  {
    id: "gs-001",
    title: "hidden camera in mannequin eye",
    date: "2025-03-04",
    episode: "ep.01",
    scene: "sc.14",
    category: "cctv",
    device: "cctv",
    aspect: "4:3",
    status: "ready",
    description:
      "covert lens embedded in a shop mannequin. fisheye coverage of the boutique floor, IR tint at night.",
    prompt:
      "covert pinhole camera feed hidden inside a mannequin eye, 4:3 fisheye distortion, boutique interior at night, infrared green-grey tint, heavy sensor noise, faint timestamp overlay top-left, dead-frame jitter, low bitrate surveillance look, gritty russian crime series prop insert",
    shortPrompt: "mannequin-eye spy cam, fisheye 4:3, IR night, gritty cctv",
    negativePrompt: "clean, color-graded, cinematic, sharp, modern UI, watermark, text logo",
    technicalNotes: [
      "aspect 4:3 / fisheye barrel distortion",
      "IR cut-off look: desaturated green-grey",
      "timestamp burned top-left, mono font",
      "sensor noise + occasional dropped frame",
    ],
  },
  {
    id: "gs-002",
    title: "timer 00:01 → 00:00",
    date: "2025-03-05",
    episode: "ep.01",
    scene: "sc.22",
    category: "hq-monitors",
    device: "monitor",
    aspect: "16:9",
    status: "shooting",
    description:
      "countdown insert for the detonation beat. seven-segment red digits ticking from 00:01 to 00:00.",
    prompt:
      "extreme close-up of a red seven-segment countdown display ticking 00:01 to 00:00, black background, slight crt bloom, shallow focus, tense crime thriller insert, faint reflection on glass, no UI chrome",
    shortPrompt: "red 7-seg countdown 00:01→00:00, crt bloom, black bg",
    negativePrompt: "colorful, playful, daytime, soft pastel, clean vector",
    technicalNotes: [
      "seven-segment red, glass reflection",
      "loop endpoint must rest on 00:00",
      "subtle crt bloom in filmed mode",
    ],
  },
  {
    id: "gs-003",
    title: "operational headquarters monitor",
    date: "2025-03-06",
    episode: "ep.02",
    scene: "sc.03",
    category: "hq-monitors",
    device: "monitor",
    aspect: "16:9",
    status: "ready",
    description:
      "task-force situation monitor: suspect grid, live map tile, case ticker along the bottom.",
    prompt:
      "police operational headquarters wall monitor, dark situation dashboard, grid of blurred suspect portraits, schematic city map tile, scrolling case ticker, muted blue-grey UI, monospace labels, faint screen glare, russian crime series prop",
    shortPrompt: "task-force situation monitor, suspect grid + map, mono UI",
    negativePrompt: "consumer app, bright saas gradient, friendly icons",
    technicalNotes: [
      "16:9 monitor, slight off-axis glare",
      "labels in cyrillic-compatible mono",
      "map tile schematic, not a real provider",
    ],
  },
  {
    id: "gs-004",
    title: "store cctv monitor",
    date: "2025-03-07",
    episode: "ep.02",
    scene: "sc.11",
    category: "cctv",
    device: "cctv",
    aspect: "4:3",
    status: "needs review",
    description: "convenience-store quad-view security monitor, four camera tiles, night timestamp.",
    prompt:
      "convenience store security monitor split into four cctv tiles, 4:3, green-grey night vision, timestamp per tile, low frame rate, heavy compression blocks, empty aisles, gritty surveillance insert",
    shortPrompt: "store quad cctv, 4 tiles, night, low fps",
    negativePrompt: "crisp, color, cinematic lighting, single clean shot",
    technicalNotes: ["quad split 2x2", "per-tile timestamp + cam id", "macroblock compression in dirty mode"],
  },
  {
    id: "gs-005",
    title: "old tv crime news",
    date: "2025-03-08",
    episode: "ep.02",
    scene: "sc.27",
    category: "tv-news",
    device: "tv",
    aspect: "16:9",
    status: "ready",
    description: "regional evening news segment about the case, lower-third ticker, channel bug.",
    prompt:
      "regional russian tv crime news broadcast on an old set, anchor desk blurred, red breaking-news lower third, scrolling ticker, channel logo bug top-right, slight crt curvature and bloom, filmed-from-screen reflection",
    shortPrompt: "old tv crime news, breaking lower-third, crt bloom",
    negativePrompt: "4k clean, modern streaming UI, flat design",
    technicalNotes: ["crt curvature + bloom", "lower third red, ticker scroll", "channel bug top-right"],
  },
  {
    id: "gs-006",
    title: "internet bank transfer",
    date: "2025-03-10",
    episode: "ep.03",
    scene: "sc.05",
    category: "bank",
    device: "monitor",
    aspect: "16:9",
    status: "draft",
    description: "online banking transfer confirmation screen, large sum, masked account, progress spinner.",
    prompt:
      "online banking transfer confirmation page on a laptop, large masked account numbers, transfer amount field, green confirm state, minimal corporate bank UI, faint screen reflection, no real brand, crime series prop insert",
    shortPrompt: "bank transfer confirm screen, masked account, large sum",
    negativePrompt: "real bank logo, brand name, playful colors",
    technicalNotes: ["fictional bank, no real brand", "mask all but last 4 digits", "green confirm accent"],
  },
  {
    id: "gs-007",
    title: "remote laptop session",
    date: "2025-03-11",
    episode: "ep.03",
    scene: "sc.18",
    category: "hq-monitors",
    device: "monitor",
    aspect: "16:9",
    status: "needs review",
    description: "remote desktop / VNC view of a target machine, command terminal, low refresh artifacts.",
    prompt:
      "remote desktop session window controlling a target laptop, terminal with scrolling commands, low refresh tearing, connection latency badge, dark hacker-adjacent but realistic UI, monospace, faint compression",
    shortPrompt: "remote desktop / VNC session, terminal, latency tearing",
    negativePrompt: "matrix rain, neon cyberpunk, fake hollywood hacking",
    technicalNotes: ["realistic remote-desktop chrome", "latency + tearing in dirty mode", "mono terminal"],
  },
  {
    id: "gs-008",
    title: "smartphone call screens",
    date: "2025-03-12",
    episode: "ep.04",
    scene: "sc.02",
    category: "phones",
    device: "phone",
    aspect: "9:16",
    status: "ready",
    description: "incoming / active call UI on a phone, unknown caller, duration counter.",
    prompt:
      "smartphone incoming call screen, unknown number, large avatar placeholder, accept/decline buttons, then active call with duration timer, clean mobile UI, 9:16, generic OS look, crime series prop",
    shortPrompt: "phone call UI, unknown caller, duration timer, 9:16",
    negativePrompt: "real OS brand, ios/android logos, playful stickers",
    technicalNotes: ["9:16 phone frame", "generic OS, no brand", "show incoming + active states"],
  },
  {
    id: "gs-009",
    title: "sms / messenger",
    date: "2025-03-12",
    episode: "ep.04",
    scene: "sc.09",
    category: "phones",
    device: "phone",
    aspect: "9:16",
    status: "ready",
    description: "threatening messenger thread, delivered/seen ticks, typing indicator, redacted names.",
    prompt:
      "phone messenger conversation thread, short threatening messages in cyrillic, delivered and seen ticks, typing indicator bubble, redacted contact name, generic chat UI, 9:16, crime series prop insert",
    shortPrompt: "messenger thread, threatening texts, ticks, 9:16",
    negativePrompt: "whatsapp/telegram exact branding, emojis everywhere",
    technicalNotes: ["generic chat UI", "delivered/seen ticks", "redacted contact"],
  },
  {
    id: "gs-010",
    title: "tropical island avatar call",
    date: "2025-03-13",
    episode: "ep.04",
    scene: "sc.31",
    category: "phones",
    device: "phone",
    aspect: "9:16",
    status: "draft",
    description: "video call to a man with a tropical island background, smug, poor connection.",
    prompt:
      "video call on a phone to a man sitting against a bright tropical island background, poor connection blocky compression, frozen frame moments, connection bars, generic call UI, 9:16, ironic crime series insert",
    shortPrompt: "video call, tropical island bg, bad connection, 9:16",
    negativePrompt: "studio quality webcam, perfect lighting",
    technicalNotes: ["freeze-frame on dropped packets", "blocky compression bursts", "bright tropical contrast vs dark UI"],
  },
  {
    id: "gs-011",
    title: "geo tracker with pulsing red dot",
    date: "2025-03-14",
    episode: "ep.05",
    scene: "sc.04",
    category: "trackers",
    device: "tablet",
    aspect: "16:10",
    status: "shooting",
    description: "live GPS tracker map, single pulsing red target dot moving along a route, coordinates HUD.",
    prompt:
      "gps tracking interface on a tablet, dark schematic map, single pulsing red target dot following a route line, live coordinates HUD, speed and heading readout, monospace, surveillance tool look, 16:10",
    shortPrompt: "gps tracker, pulsing red dot on route, coords HUD, 16:10",
    negativePrompt: "google maps branding, colorful consumer map",
    technicalNotes: ["pulsing red dot animation", "schematic map, no real provider", "coords + speed HUD mono"],
  },
  {
    id: "gs-012",
    title: "wanted bulletin cards",
    date: "2025-03-15",
    episode: "ep.05",
    scene: "sc.19",
    category: "hq-monitors",
    device: "monitor",
    aspect: "16:9",
    status: "ready",
    description: "wanted-persons bulletin board on a monitor, mugshot cards, status flags, case numbers.",
    prompt:
      "police wanted-persons bulletin on a monitor, grid of mugshot cards with case numbers and red status flags, dark database UI, monospace labels, faint glare, russian crime series prop insert",
    shortPrompt: "wanted bulletin cards, mugshots + flags, dark DB UI",
    negativePrompt: "real persons, real police logos, bright theme",
    technicalNotes: ["generated faces only", "case numbers mono", "red status flags"],
  },
  {
    id: "gs-013",
    title: "tablet gallery / case photos",
    date: "2025-03-16",
    episode: "ep.06",
    scene: "sc.07",
    category: "phones",
    device: "tablet",
    aspect: "16:10",
    status: "needs review",
    description: "case-evidence photo gallery on a tablet, thumbnail grid, swipe to enlarged photo.",
    prompt:
      "tablet photo gallery of case evidence, thumbnail grid then enlarged crime-scene photo, exif-style metadata strip, dark gallery UI, 16:10, fingerprints on glass in filmed mode, crime series prop",
    shortPrompt: "tablet evidence gallery, grid + enlarged photo, 16:10",
    negativePrompt: "vacation photos, bright cheerful gallery",
    technicalNotes: ["exif-style metadata strip", "fingerprints/glare in filmed mode", "generated evidence imagery"],
  },
  {
    id: "gs-014",
    title: "shavkat tea-house cctv",
    date: "2025-03-18",
    episode: "ep.06",
    scene: "sc.24",
    category: "cctv",
    device: "cctv",
    aspect: "4:3",
    status: "ready",
    description: "tea-house surveillance, warm interior, patrons at low tables, fixed corner angle.",
    prompt:
      "cctv of a central asian tea-house interior, warm dim lighting, patrons at low tables, fixed high corner angle, 4:3, timestamp overlay, mild compression, dropped frames, gritty surveillance insert",
    shortPrompt: "tea-house cctv, warm interior, corner angle, 4:3",
    negativePrompt: "cinematic dolly, color graded, crisp 4k",
    technicalNotes: ["fixed corner angle", "warm tungsten tint under cctv noise", "timestamp overlay"],
  },
  {
    id: "gs-015",
    title: "mansion guard post monitor",
    date: "2025-03-19",
    episode: "ep.07",
    scene: "sc.05",
    category: "cctv",
    device: "monitor",
    aspect: "16:9",
    status: "draft",
    description: "guard-post monitor at a mansion gate, multi-cam perimeter, gate + driveway tiles.",
    prompt:
      "mansion security guard post monitor, perimeter cctv tiles of gate, driveway and garden, 16:9, night ir tint on some tiles, timestamps, low fps, gritty surveillance prop insert",
    shortPrompt: "mansion guard monitor, perimeter tiles, night IR",
    negativePrompt: "single clean shot, daytime hero render",
    technicalNotes: ["mixed day/night IR tiles", "perimeter coverage", "per-tile cam id"],
  },
  {
    id: "gs-016",
    title: "industrial pipe surveillance",
    date: "2025-03-20",
    episode: "ep.07",
    scene: "sc.16",
    category: "cctv",
    device: "cctv",
    aspect: "4:3",
    status: "needs review",
    description: "industrial facility cctv, long pipe corridor, harsh sodium lighting, lone figure.",
    prompt:
      "industrial facility cctv, long corridor of pipes and valves, harsh sodium-orange lighting, lone figure walking, 4:3, sensor noise, compression, timestamp, gritty surveillance insert",
    shortPrompt: "industrial pipe corridor cctv, sodium light, lone figure",
    negativePrompt: "clean architectural render, color balanced",
    technicalNotes: ["sodium-orange harsh tint", "deep corridor perspective", "compression noise"],
  },
  {
    id: "gs-017",
    title: "abandoned hydro station hostage recording",
    date: "2025-03-22",
    episode: "ep.08",
    scene: "sc.02",
    category: "phones",
    device: "phone",
    aspect: "9:16",
    status: "shooting",
    description: "shaky vertical phone recording inside an abandoned hydroelectric station, hostage proof-of-life.",
    prompt:
      "shaky vertical phone recording inside an abandoned hydroelectric station, dim concrete hall, flashlight beam, hostage proof-of-life framing, handheld jitter, low light noise, timestamp, 9:16, harrowing crime series insert",
    shortPrompt: "shaky phone hostage recording, concrete hall, 9:16",
    negativePrompt: "stabilized, well lit, cinematic gimbal",
    technicalNotes: ["handheld jitter + low light noise", "flashlight beam falloff", "9:16 vertical"],
  },
  {
    id: "gs-018",
    title: "projector screen in hq",
    date: "2025-03-23",
    episode: "ep.08",
    scene: "sc.13",
    category: "hq-monitors",
    device: "projector",
    aspect: "16:9",
    status: "ready",
    description: "briefing projector screen, case map and connections diagram, room ambient spill.",
    prompt:
      "briefing room projector screen showing a case connections diagram and city map, 16:9, slight keystone, projector light spill and low contrast, dust in beam, monospace labels, crime series prop insert",
    shortPrompt: "hq projector briefing, connections diagram, keystone",
    negativePrompt: "high contrast monitor, crisp pixels, bright saturated",
    technicalNotes: ["keystone + low projector contrast", "light spill / washed blacks", "connections diagram"],
  },
  {
    id: "gs-019",
    title: "roadside café crime news",
    date: "2025-03-24",
    episode: "ep.09",
    scene: "sc.06",
    category: "tv-news",
    device: "tv",
    aspect: "16:9",
    status: "draft",
    description: "wall-mounted tv at a roadside café playing the crime news, ambient reflections.",
    prompt:
      "wall-mounted tv at a roadside café playing crime news, seen from across the room, reflections of café interior on the screen, lower-third ticker, slight angle, filmed-from-screen look, crime series insert",
    shortPrompt: "café wall tv crime news, room reflections, angled",
    negativePrompt: "head-on clean capture, no reflections",
    technicalNotes: ["off-axis angle", "café reflections on glass", "lower-third + ticker"],
  },
  {
    id: "gs-020",
    title: "shigorev video call",
    date: "2025-03-25",
    episode: "ep.09",
    scene: "sc.21",
    category: "phones",
    device: "monitor",
    aspect: "16:9",
    status: "needs review",
    description: "desktop video call with the character Shigorev, dim office behind him, call controls.",
    prompt:
      "desktop video call window with a stern middle-aged man (shigorev) in a dim office, call controls bar, connection quality badge, generic conferencing UI, slight compression, 16:9, crime series prop insert",
    shortPrompt: "desktop video call, shigorev, dim office, 16:9",
    negativePrompt: "zoom/teams exact branding, bright studio",
    technicalNotes: ["generic conferencing UI", "dim key light on subject", "connection badge"],
  },
  {
    id: "gs-021",
    title: "interrogation-room archive playback",
    date: "2025-03-26",
    episode: "ep.10",
    scene: "sc.04",
    category: "cctv",
    device: "monitor",
    aspect: "4:3",
    status: "ready",
    description: "archived interrogation footage played back, REC marker, scrub bar, top-down room cam.",
    prompt:
      "archived interrogation room footage playback, top-down 4:3 camera, suspect at metal table, REC dot and timecode, scrub bar overlay, vhs-like archive degradation, gritty crime series insert",
    shortPrompt: "interrogation archive playback, top cam, REC, scrub bar",
    negativePrompt: "modern crisp footage, color graded",
    technicalNotes: ["vhs-like archive degradation", "REC dot + timecode", "scrub bar overlay"],
  },
  {
    id: "gs-022",
    title: "phone used as mirror",
    date: "2025-03-27",
    episode: "ep.10",
    scene: "sc.17",
    category: "phones",
    device: "phone",
    aspect: "9:16",
    status: "draft",
    description: "front camera held as an improvised mirror to peek around a corner, dim hallway.",
    prompt:
      "phone front camera used as an improvised mirror to look around a corner, dim hallway reflection, raw camera UI, slight grain, tense crime series insert, 9:16",
    shortPrompt: "phone-as-mirror around corner, dim hallway, 9:16",
    negativePrompt: "selfie beauty filter, bright lighting",
    technicalNotes: ["raw front-camera UI", "mirrored framing", "low light grain"],
  },
  {
    id: "gs-023",
    title: "dying battery football video",
    date: "2025-03-28",
    episode: "ep.11",
    scene: "sc.03",
    category: "phones",
    device: "phone",
    aspect: "9:16",
    status: "needs review",
    description: "watching a football clip on a phone as the battery dies, 1% warning, screen dims.",
    prompt:
      "phone playing a grainy football match clip, battery at 1% red warning, screen auto-dimming, low brightness, 9:16, generic video player UI, crime series tension insert",
    shortPrompt: "football clip on dying phone, 1% battery, dimming, 9:16",
    negativePrompt: "full brightness, crisp broadcast quality",
    technicalNotes: ["1% red battery warning", "auto-dim brightness falloff", "grainy clip"],
  },
  {
    id: "gs-024",
    title: "karaev text file",
    date: "2025-03-29",
    episode: "ep.11",
    scene: "sc.20",
    category: "hq-monitors",
    device: "monitor",
    aspect: "16:9",
    status: "ready",
    description: "plain text file (karaev.txt) open in an editor, names, dates and amounts highlighted.",
    prompt:
      "plain text file karaev.txt open in a minimal code editor, monospace, lines with cyrillic names dates and amounts, some lines highlighted, dark editor theme, 16:9, crime series prop insert",
    shortPrompt: "karaev.txt in editor, mono, highlighted lines",
    negativePrompt: "rich word processor, colorful, images",
    technicalNotes: ["monospace editor, dark theme", "highlight key lines", "line numbers"],
  },
  {
    id: "gs-025",
    title: "social-media archive search",
    date: "2025-03-30",
    episode: "ep.12",
    scene: "sc.08",
    category: "hq-monitors",
    device: "monitor",
    aspect: "16:9",
    status: "draft",
    description: "investigator searching an archived social profile, results grid, timeline of posts.",
    prompt:
      "investigative tool searching an archived social media profile, generic profile header, grid of archived posts, timeline scrubber, dark osint-style UI, monospace metadata, 16:9, crime series prop",
    shortPrompt: "social archive search tool, posts grid + timeline",
    negativePrompt: "real social brand, bright consumer UI",
    technicalNotes: ["generic profile, no real brand", "archived/cached badge", "timeline scrubber"],
  },
  {
    id: "gs-026",
    title: "bondarev tablet tracker",
    date: "2025-03-31",
    episode: "ep.12",
    scene: "sc.22",
    category: "trackers",
    device: "tablet",
    aspect: "16:10",
    status: "shooting",
    description: "Bondarev's tablet showing a tracked target on a map with last-seen list and battery of beacon.",
    prompt:
      "tablet tracking app showing a single tracked target on a dark map, last-seen list panel, beacon battery indicator, pulsing marker, monospace coords, 16:10, surveillance crime series insert",
    shortPrompt: "bondarev tablet tracker, target on map, last-seen list",
    negativePrompt: "consumer maps app, colorful pins",
    technicalNotes: ["last-seen list panel", "beacon battery indicator", "pulsing marker"],
  },
  {
    id: "gs-027",
    title: "geolocation exchange: nikolskiy ↔ bondarev",
    date: "2025-04-01",
    episode: "ep.13",
    scene: "sc.05",
    category: "trackers",
    device: "phone",
    aspect: "9:16",
    status: "needs review",
    description: "two phones exchanging live location, shared-location chat bubble, two markers converging.",
    prompt:
      "phone messenger live location share between two contacts (nikolskiy and bondarev), small live map bubble with two converging markers, eta readout, generic chat UI, 9:16, crime series prop insert",
    shortPrompt: "live location share, two converging markers, eta, 9:16",
    negativePrompt: "real messenger branding, cheerful colors",
    technicalNotes: ["live-location chat bubble", "two markers converging", "eta readout mono"],
  },
]

export const getInsert = (id: string): Insert | undefined =>
  INSERTS.find((i) => i.id === id)
