import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, "../../..")
const webRoot = path.resolve(__dirname, "..")
const insertsRoot = path.join(repoRoot, "packages", "inserts")
const generatedFile = path.join(webRoot, "lib", "screenkit", "generated-inserts.ts")
const publicInsertsRoot = path.join(webRoot, "public", "screenkit-inserts")

const toIdentifier = (name) =>
  name
    .replace(/^insert-/, "")
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, ch) => ch.toUpperCase())
    .replace(/^[^a-zA-Z_$]+/, "_") || "insertPackage"

const title = (slug) =>
  slug
    .replace(/^insert-/, "")
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (ch) => ch.toUpperCase())

const readJson = (file) => {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"))
  } catch {
    return null
  }
}

const hasFile = (dir, name) => fs.existsSync(path.join(dir, name))

if (!fs.existsSync(insertsRoot)) fs.mkdirSync(insertsRoot, { recursive: true })
fs.rmSync(publicInsertsRoot, { recursive: true, force: true })
fs.mkdirSync(publicInsertsRoot, { recursive: true })

const packageImports = []
const packageRefs = []
const nextProjects = []
const categoryDefs = []
const insertDefs = []

for (const dirent of fs.readdirSync(insertsRoot, { withFileTypes: true })) {
  if (!dirent.isDirectory()) continue
  const slug = dirent.name
  const dir = path.join(insertsRoot, slug)
  const pkg = readJson(path.join(dir, "package.json"))
  const auto = readJson(path.join(dir, "screenkit.insert.json")) ?? {}
  const srcIndex = path.join(dir, "src", "index.tsx")
  const srcIndexTs = path.join(dir, "src", "index.ts")
  const isNativeInsert = fs.existsSync(srcIndex) || fs.existsSync(srcIndexTs)

  if (isNativeInsert && pkg?.name?.startsWith("@screenkit/insert-")) {
    const id = toIdentifier(slug)
    const entry = fs.existsSync(srcIndex) ? "src/index" : "src/index"
    packageImports.push(`import * as ${id} from "../../../../packages/inserts/${slug}/${entry}"`)
    packageRefs.push(id)
    continue
  }

  const looksLikeNext = hasFile(dir, "next.config.js") || hasFile(dir, "next.config.mjs") || pkg?.dependencies?.next || pkg?.devDependencies?.next
  if (!looksLikeNext) continue

  const publicSlug = slug
  const outDir = path.join(dir, "out")
  const publicDir = path.join(publicInsertsRoot, publicSlug)
  const hasStaticOutput = fs.existsSync(path.join(outDir, "index.html"))

  if (hasStaticOutput) {
    fs.cpSync(outDir, publicDir, { recursive: true })
  }

  const insertId = auto.id ?? `auto-${slug}`
  const categoryId = auto.category ?? "phones"
  const labelRu = auto.label?.ru ?? auto.title?.ru ?? title(slug)
  const labelEn = auto.label?.en ?? auto.title?.en ?? title(slug)
  const manifestLabel = auto.manifestLabel ?? labelEn

  nextProjects.push(`makeNextProjectInsertPackage({
    slug: ${JSON.stringify(publicSlug)},
    entry: ${JSON.stringify(`/screenkit-inserts/${publicSlug}/index.html`)},
    sourceDir: ${JSON.stringify(`packages/inserts/${slug}`)},
    hasStaticOutput: ${hasStaticOutput},
    manifest: {
      key: ${JSON.stringify(`next-${slug}`)},
      label: ${JSON.stringify(manifestLabel)},
      inserts: [${JSON.stringify(insertId)}],
      priority: ${Number(auto.priority ?? 50)},
    },
  })`)

  if (auto.categoryDef) {
    categoryDefs.push(JSON.stringify(auto.categoryDef, null, 2))
  }

  insertDefs.push(JSON.stringify({
    id: insertId,
    date: auto.date ?? "2026-01-01",
    episode: auto.episode ?? "auto",
    scene: auto.scene ?? slug,
    category: categoryId,
    device: auto.device ?? "phone",
    aspect: auto.aspect ?? "9:16",
    status: auto.status ?? "draft",
    title: { ru: labelRu, en: labelEn },
    description: {
      ru: auto.description?.ru ?? `автоматически подключённый next.js-проект: ${slug}`,
      en: auto.description?.en ?? `auto-linked Next.js insert project: ${slug}`,
    },
    prompt: {
      ru: auto.prompt?.ru ?? `next.js экранная вставка ${slug}`,
      en: auto.prompt?.en ?? `next.js screen insert ${slug}`,
    },
    shortPrompt: {
      ru: auto.shortPrompt?.ru ?? labelRu,
      en: auto.shortPrompt?.en ?? labelEn,
    },
    negativePrompt: {
      ru: auto.negativePrompt?.ru ?? "",
      en: auto.negativePrompt?.en ?? "",
    },
    technicalNotes: {
      ru: auto.technicalNotes?.ru ?? ["подключено автоматически из packages/inserts"],
      en: auto.technicalNotes?.en ?? ["auto-linked from packages/inserts"],
    },
  }, null, 2))
}

const content = `import type { CategoryDef, Insert } from "./types"
import type { InsertPackage } from "@screenkit/core"
import { makeNextProjectInsertPackage } from "./next-project-scene"

${packageImports.join("\n")}

// AUTO-GENERATED BY apps/web/scripts/sync-inserts.mjs
// Put native insert packages or exported Next.js projects into packages/inserts/*,
// then run pnpm --filter web sync-inserts.

export const GENERATED_NEXT_PROJECT_PACKAGES: InsertPackage[] = [
  ${nextProjects.join(",\n  ")}
]

export const GENERATED_INSERT_PACKAGES: InsertPackage[] = [
  ${packageRefs.join(",\n  ")}${packageRefs.length ? "," : ""}
  ...GENERATED_NEXT_PROJECT_PACKAGES,
]

export const GENERATED_INSERT_CATEGORIES: CategoryDef[] = [
  ${categoryDefs.join(",\n  ")}
]

export const GENERATED_INSERTS: Insert[] = [
  ${insertDefs.join(",\n  ")}
]
`

fs.mkdirSync(path.dirname(generatedFile), { recursive: true })
fs.writeFileSync(generatedFile, content)
console.log(`[screenkit] synced ${packageRefs.length} native inserts, ${nextProjects.length} next inserts`)
