import type { CategoryDef, Insert } from "./types"
import type { InsertPackage } from "@screenkit/core"
import { makeNextProjectInsertPackage } from "./next-project-scene"

import * as bankBank from "../../../../packages/inserts/bank/bank/src/index"
import * as cctvCctv from "../../../../packages/inserts/cctv/cctv/src/index"
import * as cctvCctvGrid from "../../../../packages/inserts/cctv/cctv-grid/src/index"
import * as hqMonitorsCountdown from "../../../../packages/inserts/hq-monitors/countdown/src/index"
import * as hqMonitorsRemote from "../../../../packages/inserts/hq-monitors/remote/src/index"
import * as hqMonitorsSituation from "../../../../packages/inserts/hq-monitors/situation/src/index"
import * as hqMonitorsTextFile from "../../../../packages/inserts/hq-monitors/text-file/src/index"
import * as hqMonitorsWanted from "../../../../packages/inserts/hq-monitors/wanted/src/index"
import * as phonesCall from "../../../../packages/inserts/phones/call/src/index"
import * as phonesDyingVideo from "../../../../packages/inserts/phones/dying-video/src/index"
import * as phonesMessenger from "../../../../packages/inserts/phones/messenger/src/index"
import * as trackersTracker from "../../../../packages/inserts/trackers/tracker/src/index"
import * as tvNewsTvNews from "../../../../packages/inserts/tv-news/tv-news/src/index"

// AUTO-GENERATED BY apps/web/scripts/sync-inserts.mjs
// New layout: packages/inserts/<category>/<insert>/
// Legacy layout packages/inserts/<insert>/ is still supported while old inserts are migrated.
// Then run pnpm --filter web sync-inserts.

export const GENERATED_NEXT_PROJECT_PACKAGES: InsertPackage[] = [
  
]

export const GENERATED_INSERT_PACKAGES: InsertPackage[] = [
  bankBank,
  cctvCctv,
  cctvCctvGrid,
  hqMonitorsCountdown,
  hqMonitorsRemote,
  hqMonitorsSituation,
  hqMonitorsTextFile,
  hqMonitorsWanted,
  phonesCall,
  phonesDyingVideo,
  phonesMessenger,
  trackersTracker,
  tvNewsTvNews,
  ...GENERATED_NEXT_PROJECT_PACKAGES,
]

export const GENERATED_INSERT_CATEGORIES: CategoryDef[] = [
  
]

export const GENERATED_INSERTS: Insert[] = [
  {
  "id": "gs-cctv-grid",
  "date": "2026-03-06",
  "episode": "ep.02",
  "scene": "cctv-grid",
  "category": "cctv",
  "device": "monitor",
  "aspect": "16:9",
  "status": "ready",
  "title": {
    "ru": "сетка камер видеонаблюдения",
    "en": "CCTV camera grid"
  },
  "description": {
    "ru": "мультиэкран CCTV для просмотра сразу нескольких камер: прямые ссылки на видео, папка Яндекс.Диска, Google Drive или Dropbox, автораскладка 2x2/3x3/4x4, таймкоды и подписи камер.",
    "en": "CCTV multiplexer screen for several camera feeds: direct video URLs, Yandex Disk folder, Google Drive or Dropbox, automatic 2x2/3x3/4x4 layout, timestamps and camera labels."
  },
  "prompt": {
    "ru": "экран видеонаблюдения 16:9, сетка нескольких камер cctv, мрачный монитор охраны, зеленовато-серый сигнал, таймкоды, подписи CAM 01 CAM 02, шум, scanlines, низкий битрейт, no signal плитки, реалистичная реквизитная вставка для криминального сериала",
    "en": "16:9 CCTV surveillance screen, multi-camera grid, dark security monitor, green-grey signal, timestamps, CAM 01 CAM 02 labels, noise, scanlines, low bitrate, no-signal tiles, realistic crime series prop insert"
  },
  "shortPrompt": {
    "ru": "мультиэкран CCTV 16:9, сетка камер, таймкоды, шум и no signal",
    "en": "16:9 CCTV multiplexer, camera grid, timestamps, noise and no signal"
  },
  "negativePrompt": {
    "ru": "глянцевый современный интерфейс, яркий saas, чистый vector ui, рекламный ролик, водяной знак, логотип",
    "en": "glossy modern interface, bright SaaS, clean vector UI, commercial footage, watermark, logo"
  },
  "technicalNotes": {
    "ru": [
      "соотношение вставки 16:9 / устройство monitor",
      "источники видео можно вставлять ссылками; пустой режим показывает NO SIGNAL",
      "раскладка камер: auto, 2x2, 3x3 или 4x4",
      "таймкод, подписи камер, scanlines и общий grain поверх сетки"
    ],
    "en": [
      "16:9 insert aspect / monitor device",
      "video sources can be pasted as links; empty mode shows NO SIGNAL",
      "camera layout: auto, 2x2, 3x3 or 4x4",
      "timestamp, camera labels, scanlines and shared grain over the grid"
    ]
  }
}
]
