import type { CategoryDef, Insert } from "./types"
import type { InsertPackage } from "@screenkit/core"
import { makeNextProjectInsertPackage } from "./next-project-scene"

import * as bank from "../../../../packages/inserts/bank/src/index"
import * as call from "../../../../packages/inserts/call/src/index"
import * as cctv from "../../../../packages/inserts/cctv/src/index"
import * as countdown from "../../../../packages/inserts/countdown/src/index"
import * as dyingVideo from "../../../../packages/inserts/dying-video/src/index"
import * as messenger from "../../../../packages/inserts/messenger/src/index"
import * as remote from "../../../../packages/inserts/remote/src/index"
import * as situation from "../../../../packages/inserts/situation/src/index"
import * as textFile from "../../../../packages/inserts/text-file/src/index"
import * as tracker from "../../../../packages/inserts/tracker/src/index"
import * as tvNews from "../../../../packages/inserts/tv-news/src/index"
import * as wanted from "../../../../packages/inserts/wanted/src/index"

// AUTO-GENERATED BY apps/web/scripts/sync-inserts.mjs
// Commit this file. Do not edit package imports manually.

export const GENERATED_NEXT_PROJECT_PACKAGES: InsertPackage[] = []

export const GENERATED_INSERT_PACKAGES: InsertPackage[] = [
  bank,
  call,
  cctv,
  countdown,
  dyingVideo,
  messenger,
  remote,
  situation,
  textFile,
  tracker,
  tvNews,
  wanted,
  ...GENERATED_NEXT_PROJECT_PACKAGES,
]

export const GENERATED_INSERT_CATEGORIES: CategoryDef[] = []
export const GENERATED_INSERTS: Insert[] = []

void makeNextProjectInsertPackage
