import type { CategoryDef, Insert } from "./types"
import type { InsertPackage } from "@screenkit/core"
import { makeNextProjectInsertPackage } from "./next-project-scene"

import * as bank from "../../../../packages/inserts/bank/src/index"
import * as call from "../../../../packages/inserts/call/src/index"
import * as cctv from "../../../../packages/inserts/cctv/src/index"
import * as cctvGrid from "../../../../packages/inserts/cctv-grid/src/index"
import * as countdown from "../../../../packages/inserts/countdown/src/index"
import * as dyingVideo from "../../../../packages/inserts/dying-video/src/index"
import * as messenger from "../../../../packages/inserts/messenger/src/index"
import * as remote from "../../../../packages/inserts/remote/src/index"
import * as situation from "../../../../packages/inserts/situation/src/index"
import * as textFile from "../../../../packages/inserts/text-file/src/index"
import * as tracker from "../../../../packages/inserts/tracker/src/index"
import * as tvNews from "../../../../packages/inserts/tv-news/src/index"
import * as wanted from "../../../../packages/inserts/wanted/src/index"

// AUTO-GENERATED BY apps/web/scripts/sync-inserts.mjs
// Put native insert packages or exported Next.js projects into packages/inserts/*,
// then run pnpm --filter web sync-inserts.

export const GENERATED_NEXT_PROJECT_PACKAGES: InsertPackage[] = [
  
]

export const GENERATED_INSERT_PACKAGES: InsertPackage[] = [
  bank,
  call,
  cctv,
  cctvGrid,
  countdown,
  dyingVideo,
  messenger,
  remote,
  situation,
  textFile,
  tracker,
  tvNews,
  wanted,
  ...GENERATED_NEXT_PROJECT_PACKAGES,
]

export const GENERATED_INSERT_CATEGORIES: CategoryDef[] = [
  
]

export const GENERATED_INSERTS: Insert[] = [
  {
    id: "gs-cctv-grid",
    date: "2026-03-06",
    episode: "ep.02",
    scene: "cctv-grid",
    category: "cctv",
    device: "monitor",
    aspect: "16:9",
    status: "ready",
    title: {
      ru: "сетка камер видеонаблюдения",
      en: "CCTV camera grid",
    },
    description: {
      ru: "мультиэкран CCTV для просмотра сразу нескольких камер: прямые ссылки на видео, папка Яндекс.Диска, Google Drive или Dropbox, автораскладка 2x2/3x3/4x4, таймкоды и подписи камер.",
      en: "CCTV multiplexer screen for several camera feeds: direct video URLs, Yandex Disk folder, Google Drive or Dropbox, automatic 2x2/3x3/4x4 layout, timestamps and camera labels.",
    },
    prompt: {
      ru: "экран видеонаблюдения 16:9, сетка нескольких камер cctv, мрачный монитор охраны, зеленовато-серый сигнал, таймкоды, подписи CAM 01 CAM 02, шум, scanlines, низкий битрейт, no signal плитки, реалистичная реквизитная вставка для криминального сериала",
      en: "16:9 CCTV surveillance screen, multi-camera grid, dark security monitor, green-grey signal, timestamps, CAM 01 CAM 02 labels, noise, scanlines, low bitrate, no-signal tiles, realistic crime series prop insert",
    },
    shortPrompt: {
      ru: "мультиэкран CCTV 16:9, сетка камер, таймкоды, шум и no signal",
      en: "16:9 CCTV multiplexer, camera grid, timestamps, noise and no signal",
    },
    negativePrompt: {
      ru: "глянцевый современный интерфейс, яркий saas, чистый vector ui, рекламный ролик, водяной знак, логотип",
      en: "glossy modern interface, bright SaaS, clean vector UI, commercial footage, watermark, logo",
    },
    technicalNotes: {
      ru: [
        "соотношение вставки 16:9 / устройство monitor",
        "источники видео можно вставлять ссылками; пустой режим показывает NO SIGNAL",
        "раскладка камер: auto, 2x2, 3x3 или 4x4",
        "таймкод, подписи камер, scanlines и общий grain поверх сетки",
      ],
      en: [
        "16:9 insert aspect / monitor device",
        "video sources can be pasted as links; empty mode shows NO SIGNAL",
        "camera layout: auto, 2x2, 3x3 or 4x4",
        "timestamp, camera labels, scanlines and shared grain over the grid",
      ],
    },
  },
]
